export interface Country {
  name: string;
  iso2: string;
  dialCode: string;
  flag: string;
  /** adjective form for nationality field */
  nationality: string;
}

export const COUNTRIES: Country[] = [
  {
    name: 'Afghanistan',
    iso2: 'AF',
    dialCode: '+93',
    flag: '🇦🇫',
    nationality: 'Afghan',
  },
  {
    name: 'Albania',
    iso2: 'AL',
    dialCode: '+355',
    flag: '🇦🇱',
    nationality: 'Albanian',
  },
  {
    name: 'Algeria',
    iso2: 'DZ',
    dialCode: '+213',
    flag: '🇩🇿',
    nationality: 'Algerian',
  },
  {
    name: 'Andorra',
    iso2: 'AD',
    dialCode: '+376',
    flag: '🇦🇩',
    nationality: 'Andorran',
  },
  {
    name: 'Angola',
    iso2: 'AO',
    dialCode: '+244',
    flag: '🇦🇴',
    nationality: 'Angolan',
  },
  {
    name: 'Argentina',
    iso2: 'AR',
    dialCode: '+54',
    flag: '🇦🇷',
    nationality: 'Argentine',
  },
  {
    name: 'Armenia',
    iso2: 'AM',
    dialCode: '+374',
    flag: '🇦🇲',
    nationality: 'Armenian',
  },
  {
    name: 'Australia',
    iso2: 'AU',
    dialCode: '+61',
    flag: '🇦🇺',
    nationality: 'Australian',
  },
  {
    name: 'Austria',
    iso2: 'AT',
    dialCode: '+43',
    flag: '🇦🇹',
    nationality: 'Austrian',
  },
  {
    name: 'Azerbaijan',
    iso2: 'AZ',
    dialCode: '+994',
    flag: '🇦🇿',
    nationality: 'Azerbaijani',
  },
  {
    name: 'Bahrain',
    iso2: 'BH',
    dialCode: '+973',
    flag: '🇧🇭',
    nationality: 'Bahraini',
  },
  {
    name: 'Bangladesh',
    iso2: 'BD',
    dialCode: '+880',
    flag: '🇧🇩',
    nationality: 'Bangladeshi',
  },
  {
    name: 'Belarus',
    iso2: 'BY',
    dialCode: '+375',
    flag: '🇧🇾',
    nationality: 'Belarusian',
  },
  {
    name: 'Belgium',
    iso2: 'BE',
    dialCode: '+32',
    flag: '🇧🇪',
    nationality: 'Belgian',
  },
  {
    name: 'Belize',
    iso2: 'BZ',
    dialCode: '+501',
    flag: '🇧🇿',
    nationality: 'Belizean',
  },
  {
    name: 'Benin',
    iso2: 'BJ',
    dialCode: '+229',
    flag: '🇧🇯',
    nationality: 'Beninese',
  },
  {
    name: 'Bhutan',
    iso2: 'BT',
    dialCode: '+975',
    flag: '🇧🇹',
    nationality: 'Bhutanese',
  },
  {
    name: 'Bolivia',
    iso2: 'BO',
    dialCode: '+591',
    flag: '🇧🇴',
    nationality: 'Bolivian',
  },
  {
    name: 'Bosnia and Herzegovina',
    iso2: 'BA',
    dialCode: '+387',
    flag: '🇧🇦',
    nationality: 'Bosnian',
  },
  {
    name: 'Botswana',
    iso2: 'BW',
    dialCode: '+267',
    flag: '🇧🇼',
    nationality: 'Botswanan',
  },
  {
    name: 'Brazil',
    iso2: 'BR',
    dialCode: '+55',
    flag: '🇧🇷',
    nationality: 'Brazilian',
  },
  {
    name: 'Brunei',
    iso2: 'BN',
    dialCode: '+673',
    flag: '🇧🇳',
    nationality: 'Bruneian',
  },
  {
    name: 'Bulgaria',
    iso2: 'BG',
    dialCode: '+359',
    flag: '🇧🇬',
    nationality: 'Bulgarian',
  },
  {
    name: 'Burkina Faso',
    iso2: 'BF',
    dialCode: '+226',
    flag: '🇧🇫',
    nationality: 'Burkinabe',
  },
  {
    name: 'Burundi',
    iso2: 'BI',
    dialCode: '+257',
    flag: '🇧🇮',
    nationality: 'Burundian',
  },
  {
    name: 'Cambodia',
    iso2: 'KH',
    dialCode: '+855',
    flag: '🇰🇭',
    nationality: 'Cambodian',
  },
  {
    name: 'Cameroon',
    iso2: 'CM',
    dialCode: '+237',
    flag: '🇨🇲',
    nationality: 'Cameroonian',
  },
  {
    name: 'Canada',
    iso2: 'CA',
    dialCode: '+1',
    flag: '🇨🇦',
    nationality: 'Canadian',
  },
  {
    name: 'Cape Verde',
    iso2: 'CV',
    dialCode: '+238',
    flag: '🇨🇻',
    nationality: 'Cape Verdean',
  },
  {
    name: 'Central African Republic',
    iso2: 'CF',
    dialCode: '+236',
    flag: '🇨🇫',
    nationality: 'Central African',
  },
  {
    name: 'Chad',
    iso2: 'TD',
    dialCode: '+235',
    flag: '🇹🇩',
    nationality: 'Chadian',
  },
  {
    name: 'Chile',
    iso2: 'CL',
    dialCode: '+56',
    flag: '🇨🇱',
    nationality: 'Chilean',
  },
  {
    name: 'China',
    iso2: 'CN',
    dialCode: '+86',
    flag: '🇨🇳',
    nationality: 'Chinese',
  },
  {
    name: 'Colombia',
    iso2: 'CO',
    dialCode: '+57',
    flag: '🇨🇴',
    nationality: 'Colombian',
  },
  {
    name: 'Comoros',
    iso2: 'KM',
    dialCode: '+269',
    flag: '🇰🇲',
    nationality: 'Comorian',
  },
  {
    name: 'Congo',
    iso2: 'CG',
    dialCode: '+242',
    flag: '🇨🇬',
    nationality: 'Congolese',
  },
  {
    name: 'Costa Rica',
    iso2: 'CR',
    dialCode: '+506',
    flag: '🇨🇷',
    nationality: 'Costa Rican',
  },
  {
    name: "Côte d'Ivoire",
    iso2: 'CI',
    dialCode: '+225',
    flag: '🇨🇮',
    nationality: 'Ivorian',
  },
  {
    name: 'Croatia',
    iso2: 'HR',
    dialCode: '+385',
    flag: '🇭🇷',
    nationality: 'Croatian',
  },
  {
    name: 'Cuba',
    iso2: 'CU',
    dialCode: '+53',
    flag: '🇨🇺',
    nationality: 'Cuban',
  },
  {
    name: 'Cyprus',
    iso2: 'CY',
    dialCode: '+357',
    flag: '🇨🇾',
    nationality: 'Cypriot',
  },
  {
    name: 'Czech Republic',
    iso2: 'CZ',
    dialCode: '+420',
    flag: '🇨🇿',
    nationality: 'Czech',
  },
  {
    name: 'DR Congo',
    iso2: 'CD',
    dialCode: '+243',
    flag: '🇨🇩',
    nationality: 'Congolese',
  },
  {
    name: 'Denmark',
    iso2: 'DK',
    dialCode: '+45',
    flag: '🇩🇰',
    nationality: 'Danish',
  },
  {
    name: 'Djibouti',
    iso2: 'DJ',
    dialCode: '+253',
    flag: '🇩🇯',
    nationality: 'Djiboutian',
  },
  {
    name: 'Dominican Republic',
    iso2: 'DO',
    dialCode: '+1-809',
    flag: '🇩🇴',
    nationality: 'Dominican',
  },
  {
    name: 'Ecuador',
    iso2: 'EC',
    dialCode: '+593',
    flag: '🇪🇨',
    nationality: 'Ecuadorian',
  },
  {
    name: 'Egypt',
    iso2: 'EG',
    dialCode: '+20',
    flag: '🇪🇬',
    nationality: 'Egyptian',
  },
  {
    name: 'El Salvador',
    iso2: 'SV',
    dialCode: '+503',
    flag: '🇸🇻',
    nationality: 'Salvadoran',
  },
  {
    name: 'Equatorial Guinea',
    iso2: 'GQ',
    dialCode: '+240',
    flag: '🇬🇶',
    nationality: 'Equatoguinean',
  },
  {
    name: 'Eritrea',
    iso2: 'ER',
    dialCode: '+291',
    flag: '🇪🇷',
    nationality: 'Eritrean',
  },
  {
    name: 'Estonia',
    iso2: 'EE',
    dialCode: '+372',
    flag: '🇪🇪',
    nationality: 'Estonian',
  },
  {
    name: 'Eswatini',
    iso2: 'SZ',
    dialCode: '+268',
    flag: '🇸🇿',
    nationality: 'Swazi',
  },
  {
    name: 'Ethiopia',
    iso2: 'ET',
    dialCode: '+251',
    flag: '🇪🇹',
    nationality: 'Ethiopian',
  },
  {
    name: 'Fiji',
    iso2: 'FJ',
    dialCode: '+679',
    flag: '🇫🇯',
    nationality: 'Fijian',
  },
  {
    name: 'Finland',
    iso2: 'FI',
    dialCode: '+358',
    flag: '🇫🇮',
    nationality: 'Finnish',
  },
  {
    name: 'France',
    iso2: 'FR',
    dialCode: '+33',
    flag: '🇫🇷',
    nationality: 'French',
  },
  {
    name: 'Gabon',
    iso2: 'GA',
    dialCode: '+241',
    flag: '🇬🇦',
    nationality: 'Gabonese',
  },
  {
    name: 'Gambia',
    iso2: 'GM',
    dialCode: '+220',
    flag: '🇬🇲',
    nationality: 'Gambian',
  },
  {
    name: 'Georgia',
    iso2: 'GE',
    dialCode: '+995',
    flag: '🇬🇪',
    nationality: 'Georgian',
  },
  {
    name: 'Germany',
    iso2: 'DE',
    dialCode: '+49',
    flag: '🇩🇪',
    nationality: 'German',
  },
  {
    name: 'Ghana',
    iso2: 'GH',
    dialCode: '+233',
    flag: '🇬🇭',
    nationality: 'Ghanaian',
  },
  {
    name: 'Greece',
    iso2: 'GR',
    dialCode: '+30',
    flag: '🇬🇷',
    nationality: 'Greek',
  },
  {
    name: 'Guatemala',
    iso2: 'GT',
    dialCode: '+502',
    flag: '🇬🇹',
    nationality: 'Guatemalan',
  },
  {
    name: 'Guinea',
    iso2: 'GN',
    dialCode: '+224',
    flag: '🇬🇳',
    nationality: 'Guinean',
  },
  {
    name: 'Guinea-Bissau',
    iso2: 'GW',
    dialCode: '+245',
    flag: '🇬🇼',
    nationality: 'Guinean',
  },
  {
    name: 'Guyana',
    iso2: 'GY',
    dialCode: '+592',
    flag: '🇬🇾',
    nationality: 'Guyanese',
  },
  {
    name: 'Haiti',
    iso2: 'HT',
    dialCode: '+509',
    flag: '🇭🇹',
    nationality: 'Haitian',
  },
  {
    name: 'Honduras',
    iso2: 'HN',
    dialCode: '+504',
    flag: '🇭🇳',
    nationality: 'Honduran',
  },
  {
    name: 'Hungary',
    iso2: 'HU',
    dialCode: '+36',
    flag: '🇭🇺',
    nationality: 'Hungarian',
  },
  {
    name: 'Iceland',
    iso2: 'IS',
    dialCode: '+354',
    flag: '🇮🇸',
    nationality: 'Icelandic',
  },
  {
    name: 'India',
    iso2: 'IN',
    dialCode: '+91',
    flag: '🇮🇳',
    nationality: 'Indian',
  },
  {
    name: 'Indonesia',
    iso2: 'ID',
    dialCode: '+62',
    flag: '🇮🇩',
    nationality: 'Indonesian',
  },
  {
    name: 'Iran',
    iso2: 'IR',
    dialCode: '+98',
    flag: '🇮🇷',
    nationality: 'Iranian',
  },
  {
    name: 'Iraq',
    iso2: 'IQ',
    dialCode: '+964',
    flag: '🇮🇶',
    nationality: 'Iraqi',
  },
  {
    name: 'Ireland',
    iso2: 'IE',
    dialCode: '+353',
    flag: '🇮🇪',
    nationality: 'Irish',
  },
  {
    name: 'Israel',
    iso2: 'IL',
    dialCode: '+972',
    flag: '🇮🇱',
    nationality: 'Israeli',
  },
  {
    name: 'Italy',
    iso2: 'IT',
    dialCode: '+39',
    flag: '🇮🇹',
    nationality: 'Italian',
  },
  {
    name: 'Jamaica',
    iso2: 'JM',
    dialCode: '+1-876',
    flag: '🇯🇲',
    nationality: 'Jamaican',
  },
  {
    name: 'Japan',
    iso2: 'JP',
    dialCode: '+81',
    flag: '🇯🇵',
    nationality: 'Japanese',
  },
  {
    name: 'Jordan',
    iso2: 'JO',
    dialCode: '+962',
    flag: '🇯🇴',
    nationality: 'Jordanian',
  },
  {
    name: 'Kazakhstan',
    iso2: 'KZ',
    dialCode: '+7',
    flag: '🇰🇿',
    nationality: 'Kazakhstani',
  },
  {
    name: 'Kenya',
    iso2: 'KE',
    dialCode: '+254',
    flag: '🇰🇪',
    nationality: 'Kenyan',
  },
  {
    name: 'Kuwait',
    iso2: 'KW',
    dialCode: '+965',
    flag: '🇰🇼',
    nationality: 'Kuwaiti',
  },
  {
    name: 'Kyrgyzstan',
    iso2: 'KG',
    dialCode: '+996',
    flag: '🇰🇬',
    nationality: 'Kyrgyz',
  },
  {
    name: 'Laos',
    iso2: 'LA',
    dialCode: '+856',
    flag: '🇱🇦',
    nationality: 'Laotian',
  },
  {
    name: 'Latvia',
    iso2: 'LV',
    dialCode: '+371',
    flag: '🇱🇻',
    nationality: 'Latvian',
  },
  {
    name: 'Lebanon',
    iso2: 'LB',
    dialCode: '+961',
    flag: '🇱🇧',
    nationality: 'Lebanese',
  },
  {
    name: 'Lesotho',
    iso2: 'LS',
    dialCode: '+266',
    flag: '🇱🇸',
    nationality: 'Basotho',
  },
  {
    name: 'Liberia',
    iso2: 'LR',
    dialCode: '+231',
    flag: '🇱🇷',
    nationality: 'Liberian',
  },
  {
    name: 'Libya',
    iso2: 'LY',
    dialCode: '+218',
    flag: '🇱🇾',
    nationality: 'Libyan',
  },
  {
    name: 'Liechtenstein',
    iso2: 'LI',
    dialCode: '+423',
    flag: '🇱🇮',
    nationality: 'Liechtensteiner',
  },
  {
    name: 'Lithuania',
    iso2: 'LT',
    dialCode: '+370',
    flag: '🇱🇹',
    nationality: 'Lithuanian',
  },
  {
    name: 'Luxembourg',
    iso2: 'LU',
    dialCode: '+352',
    flag: '🇱🇺',
    nationality: 'Luxembourgish',
  },
  {
    name: 'Madagascar',
    iso2: 'MG',
    dialCode: '+261',
    flag: '🇲🇬',
    nationality: 'Malagasy',
  },
  {
    name: 'Malawi',
    iso2: 'MW',
    dialCode: '+265',
    flag: '🇲🇼',
    nationality: 'Malawian',
  },
  {
    name: 'Malaysia',
    iso2: 'MY',
    dialCode: '+60',
    flag: '🇲🇾',
    nationality: 'Malaysian',
  },
  {
    name: 'Maldives',
    iso2: 'MV',
    dialCode: '+960',
    flag: '🇲🇻',
    nationality: 'Maldivian',
  },
  {
    name: 'Mali',
    iso2: 'ML',
    dialCode: '+223',
    flag: '🇲🇱',
    nationality: 'Malian',
  },
  {
    name: 'Malta',
    iso2: 'MT',
    dialCode: '+356',
    flag: '🇲🇹',
    nationality: 'Maltese',
  },
  {
    name: 'Mauritania',
    iso2: 'MR',
    dialCode: '+222',
    flag: '🇲🇷',
    nationality: 'Mauritanian',
  },
  {
    name: 'Mauritius',
    iso2: 'MU',
    dialCode: '+230',
    flag: '🇲🇺',
    nationality: 'Mauritian',
  },
  {
    name: 'Mexico',
    iso2: 'MX',
    dialCode: '+52',
    flag: '🇲🇽',
    nationality: 'Mexican',
  },
  {
    name: 'Moldova',
    iso2: 'MD',
    dialCode: '+373',
    flag: '🇲🇩',
    nationality: 'Moldovan',
  },
  {
    name: 'Monaco',
    iso2: 'MC',
    dialCode: '+377',
    flag: '🇲🇨',
    nationality: 'Monégasque',
  },
  {
    name: 'Mongolia',
    iso2: 'MN',
    dialCode: '+976',
    flag: '🇲🇳',
    nationality: 'Mongolian',
  },
  {
    name: 'Montenegro',
    iso2: 'ME',
    dialCode: '+382',
    flag: '🇲🇪',
    nationality: 'Montenegrin',
  },
  {
    name: 'Morocco',
    iso2: 'MA',
    dialCode: '+212',
    flag: '🇲🇦',
    nationality: 'Moroccan',
  },
  {
    name: 'Mozambique',
    iso2: 'MZ',
    dialCode: '+258',
    flag: '🇲🇿',
    nationality: 'Mozambican',
  },
  {
    name: 'Myanmar',
    iso2: 'MM',
    dialCode: '+95',
    flag: '🇲🇲',
    nationality: 'Burmese',
  },
  {
    name: 'Namibia',
    iso2: 'NA',
    dialCode: '+264',
    flag: '🇳🇦',
    nationality: 'Namibian',
  },
  {
    name: 'Nepal',
    iso2: 'NP',
    dialCode: '+977',
    flag: '🇳🇵',
    nationality: 'Nepali',
  },
  {
    name: 'Netherlands',
    iso2: 'NL',
    dialCode: '+31',
    flag: '🇳🇱',
    nationality: 'Dutch',
  },
  {
    name: 'New Zealand',
    iso2: 'NZ',
    dialCode: '+64',
    flag: '🇳🇿',
    nationality: 'New Zealander',
  },
  {
    name: 'Nicaragua',
    iso2: 'NI',
    dialCode: '+505',
    flag: '🇳🇮',
    nationality: 'Nicaraguan',
  },
  {
    name: 'Niger',
    iso2: 'NE',
    dialCode: '+227',
    flag: '🇳🇪',
    nationality: 'Nigerien',
  },
  {
    name: 'Nigeria',
    iso2: 'NG',
    dialCode: '+234',
    flag: '🇳🇬',
    nationality: 'Nigerian',
  },
  {
    name: 'North Korea',
    iso2: 'KP',
    dialCode: '+850',
    flag: '🇰🇵',
    nationality: 'North Korean',
  },
  {
    name: 'North Macedonia',
    iso2: 'MK',
    dialCode: '+389',
    flag: '🇲🇰',
    nationality: 'Macedonian',
  },
  {
    name: 'Norway',
    iso2: 'NO',
    dialCode: '+47',
    flag: '🇳🇴',
    nationality: 'Norwegian',
  },
  {
    name: 'Oman',
    iso2: 'OM',
    dialCode: '+968',
    flag: '🇴🇲',
    nationality: 'Omani',
  },
  {
    name: 'Pakistan',
    iso2: 'PK',
    dialCode: '+92',
    flag: '🇵🇰',
    nationality: 'Pakistani',
  },
  {
    name: 'Palestine',
    iso2: 'PS',
    dialCode: '+970',
    flag: '🇵🇸',
    nationality: 'Palestinian',
  },
  {
    name: 'Panama',
    iso2: 'PA',
    dialCode: '+507',
    flag: '🇵🇦',
    nationality: 'Panamanian',
  },
  {
    name: 'Papua New Guinea',
    iso2: 'PG',
    dialCode: '+675',
    flag: '🇵🇬',
    nationality: 'Papua New Guinean',
  },
  {
    name: 'Paraguay',
    iso2: 'PY',
    dialCode: '+595',
    flag: '🇵🇾',
    nationality: 'Paraguayan',
  },
  {
    name: 'Peru',
    iso2: 'PE',
    dialCode: '+51',
    flag: '🇵🇪',
    nationality: 'Peruvian',
  },
  {
    name: 'Philippines',
    iso2: 'PH',
    dialCode: '+63',
    flag: '🇵🇭',
    nationality: 'Filipino',
  },
  {
    name: 'Poland',
    iso2: 'PL',
    dialCode: '+48',
    flag: '🇵🇱',
    nationality: 'Polish',
  },
  {
    name: 'Portugal',
    iso2: 'PT',
    dialCode: '+351',
    flag: '🇵🇹',
    nationality: 'Portuguese',
  },
  {
    name: 'Qatar',
    iso2: 'QA',
    dialCode: '+974',
    flag: '🇶🇦',
    nationality: 'Qatari',
  },
  {
    name: 'Romania',
    iso2: 'RO',
    dialCode: '+40',
    flag: '🇷🇴',
    nationality: 'Romanian',
  },
  {
    name: 'Russia',
    iso2: 'RU',
    dialCode: '+7',
    flag: '🇷🇺',
    nationality: 'Russian',
  },
  {
    name: 'Rwanda',
    iso2: 'RW',
    dialCode: '+250',
    flag: '🇷🇼',
    nationality: 'Rwandan',
  },
  {
    name: 'Saudi Arabia',
    iso2: 'SA',
    dialCode: '+966',
    flag: '🇸🇦',
    nationality: 'Saudi',
  },
  {
    name: 'Senegal',
    iso2: 'SN',
    dialCode: '+221',
    flag: '🇸🇳',
    nationality: 'Senegalese',
  },
  {
    name: 'Serbia',
    iso2: 'RS',
    dialCode: '+381',
    flag: '🇷🇸',
    nationality: 'Serbian',
  },
  {
    name: 'Sierra Leone',
    iso2: 'SL',
    dialCode: '+232',
    flag: '🇸🇱',
    nationality: 'Sierra Leonean',
  },
  {
    name: 'Singapore',
    iso2: 'SG',
    dialCode: '+65',
    flag: '🇸🇬',
    nationality: 'Singaporean',
  },
  {
    name: 'Slovakia',
    iso2: 'SK',
    dialCode: '+421',
    flag: '🇸🇰',
    nationality: 'Slovak',
  },
  {
    name: 'Slovenia',
    iso2: 'SI',
    dialCode: '+386',
    flag: '🇸🇮',
    nationality: 'Slovenian',
  },
  {
    name: 'Somalia',
    iso2: 'SO',
    dialCode: '+252',
    flag: '🇸🇴',
    nationality: 'Somali',
  },
  {
    name: 'South Africa',
    iso2: 'ZA',
    dialCode: '+27',
    flag: '🇿🇦',
    nationality: 'South African',
  },
  {
    name: 'South Korea',
    iso2: 'KR',
    dialCode: '+82',
    flag: '🇰🇷',
    nationality: 'South Korean',
  },
  {
    name: 'South Sudan',
    iso2: 'SS',
    dialCode: '+211',
    flag: '🇸🇸',
    nationality: 'South Sudanese',
  },
  {
    name: 'Spain',
    iso2: 'ES',
    dialCode: '+34',
    flag: '🇪🇸',
    nationality: 'Spanish',
  },
  {
    name: 'Sri Lanka',
    iso2: 'LK',
    dialCode: '+94',
    flag: '🇱🇰',
    nationality: 'Sri Lankan',
  },
  {
    name: 'Sudan',
    iso2: 'SD',
    dialCode: '+249',
    flag: '🇸🇩',
    nationality: 'Sudanese',
  },
  {
    name: 'Suriname',
    iso2: 'SR',
    dialCode: '+597',
    flag: '🇸🇷',
    nationality: 'Surinamese',
  },
  {
    name: 'Sweden',
    iso2: 'SE',
    dialCode: '+46',
    flag: '🇸🇪',
    nationality: 'Swedish',
  },
  {
    name: 'Switzerland',
    iso2: 'CH',
    dialCode: '+41',
    flag: '🇨🇭',
    nationality: 'Swiss',
  },
  {
    name: 'Syria',
    iso2: 'SY',
    dialCode: '+963',
    flag: '🇸🇾',
    nationality: 'Syrian',
  },
  {
    name: 'Taiwan',
    iso2: 'TW',
    dialCode: '+886',
    flag: '🇹🇼',
    nationality: 'Taiwanese',
  },
  {
    name: 'Tajikistan',
    iso2: 'TJ',
    dialCode: '+992',
    flag: '🇹🇯',
    nationality: 'Tajik',
  },
  {
    name: 'Tanzania',
    iso2: 'TZ',
    dialCode: '+255',
    flag: '🇹🇿',
    nationality: 'Tanzanian',
  },
  {
    name: 'Thailand',
    iso2: 'TH',
    dialCode: '+66',
    flag: '🇹🇭',
    nationality: 'Thai',
  },
  {
    name: 'Timor-Leste',
    iso2: 'TL',
    dialCode: '+670',
    flag: '🇹🇱',
    nationality: 'Timorese',
  },
  {
    name: 'Togo',
    iso2: 'TG',
    dialCode: '+228',
    flag: '🇹🇬',
    nationality: 'Togolese',
  },
  {
    name: 'Trinidad and Tobago',
    iso2: 'TT',
    dialCode: '+1-868',
    flag: '🇹🇹',
    nationality: 'Trinidadian',
  },
  {
    name: 'Tunisia',
    iso2: 'TN',
    dialCode: '+216',
    flag: '🇹🇳',
    nationality: 'Tunisian',
  },
  {
    name: 'Turkey',
    iso2: 'TR',
    dialCode: '+90',
    flag: '🇹🇷',
    nationality: 'Turkish',
  },
  {
    name: 'Turkmenistan',
    iso2: 'TM',
    dialCode: '+993',
    flag: '🇹🇲',
    nationality: 'Turkmen',
  },
  {
    name: 'Uganda',
    iso2: 'UG',
    dialCode: '+256',
    flag: '🇺🇬',
    nationality: 'Ugandan',
  },
  {
    name: 'Ukraine',
    iso2: 'UA',
    dialCode: '+380',
    flag: '🇺🇦',
    nationality: 'Ukrainian',
  },
  {
    name: 'United Arab Emirates',
    iso2: 'AE',
    dialCode: '+971',
    flag: '🇦🇪',
    nationality: 'Emirati',
  },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    dialCode: '+44',
    flag: '🇬🇧',
    nationality: 'British',
  },
  {
    name: 'United States',
    iso2: 'US',
    dialCode: '+1',
    flag: '🇺🇸',
    nationality: 'American',
  },
  {
    name: 'Uruguay',
    iso2: 'UY',
    dialCode: '+598',
    flag: '🇺🇾',
    nationality: 'Uruguayan',
  },
  {
    name: 'Uzbekistan',
    iso2: 'UZ',
    dialCode: '+998',
    flag: '🇺🇿',
    nationality: 'Uzbek',
  },
  {
    name: 'Venezuela',
    iso2: 'VE',
    dialCode: '+58',
    flag: '🇻🇪',
    nationality: 'Venezuelan',
  },
  {
    name: 'Vietnam',
    iso2: 'VN',
    dialCode: '+84',
    flag: '🇻🇳',
    nationality: 'Vietnamese',
  },
  {
    name: 'Yemen',
    iso2: 'YE',
    dialCode: '+967',
    flag: '🇾🇪',
    nationality: 'Yemeni',
  },
  {
    name: 'Zambia',
    iso2: 'ZM',
    dialCode: '+260',
    flag: '🇿🇲',
    nationality: 'Zambian',
  },
  {
    name: 'Zimbabwe',
    iso2: 'ZW',
    dialCode: '+263',
    flag: '🇿🇼',
    nationality: 'Zimbabwean',
  },
];

export function searchCountries(query: string): Country[] {
  const q = query.toLowerCase().trim();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.iso2.toLowerCase().includes(q) ||
      c.dialCode.includes(q) ||
      c.nationality.toLowerCase().includes(q),
  );
}
